fix for GHC built with Hadrian

diff --git a/config b/config
--- a/config
+++ b/config
@@ -32,13 +32,41 @@ then
     NGX_HASKELL_MODULE_LIBDL="$NGX_LIBDL"
 fi
 
+if test -z "$GHC_PROGRAM"
+then
+    ngx_ghc_program=ghc
+else
+    ngx_ghc_program="$GHC_PROGRAM"
+fi
+
+if ! command -v "$ngx_ghc_program" > /dev/null 2>&1
+then
+    echo "$0: error: unable to find ghc executable!"
+    echo "   Check that GHC is installed "`
+        `"or specify environment variable GHC_PROGRAM"
+    exit 1
+fi
+
+ngx_ghc_include_path="$($ngx_ghc_program --print-libdir)/include"
+if test ! -e "$ngx_ghc_include_path"
+then
+    # GHC built with Hadrian may put include/ path at one level upper,
+    # see https://gitlab.haskell.org/ghc/ghc/-/issues/21609
+    ngx_ghc_include_path="$($ngx_ghc_program --print-libdir)/../include"
+    if test ! -e "$ngx_ghc_include_path"
+    then
+        echo "$0: error: unable to find GHC include/ path!"
+        exit 1
+    fi
+fi
+
 if test -n "$ngx_module_link"
 then
     ngx_module_type=HTTP
     ngx_module_name=$ngx_addon_name
     ngx_module_deps="$NGX_HTTP_HASKELL_MODULE_DEPS"
     ngx_module_srcs="$NGX_HTTP_HASKELL_MODULE_SRCS"
-    ngx_module_incs="$(ghc --print-libdir)/include"
+    ngx_module_incs="$ngx_ghc_include_path"
     ngx_module_libs="$NGX_HASKELL_MODULE_LIBDL"
 
     . auto/module
@@ -66,7 +94,7 @@ else
     HTTP_MODULES="$HTTP_MODULES $ngx_addon_name"
     NGX_ADDON_DEPS="$NGX_ADDON_DEPS $NGX_HTTP_HASKELL_MODULE_DEPS"
     NGX_ADDON_SRCS="$NGX_ADDON_SRCS $NGX_HTTP_HASKELL_MODULE_SRCS"
-    CFLAGS="$CFLAGS -I$(ghc --print-libdir)/include"
+    CFLAGS="$CFLAGS -I$ngx_ghc_include_path"
     CORE_LIBS="$CORE_LIBS $NGX_HASKELL_MODULE_LIBDL"
 fi
 
